# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\ui\LoginUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Login(object):
    def setupUi(self, Login):
        Login.setObjectName("Login")
        Login.resize(263, 273)
        Login.setLayoutDirection(QtCore.Qt.LeftToRight)
        
        pixmap = QtGui.QPixmap(".\data\pic.jpg")
        self.lbl = QtWidgets.QLabel(Login)
        self.lbl.setPixmap(pixmap)
        self.lbl.setGeometry(QtCore.QRect(80, 20, 100, 64))

        self.enterButton = QtWidgets.QPushButton(Login)
        self.enterButton.setGeometry(QtCore.QRect(82, 220, 101, 28))
        self.enterButton.setObjectName("enterButton")
        self.login = QtWidgets.QLineEdit(Login)
        self.login.setEnabled(True)
        self.login.setGeometry(QtCore.QRect(20, 140, 221, 22))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.login.sizePolicy().hasHeightForWidth())
        self.login.setSizePolicy(sizePolicy)
        self.login.setTabletTracking(True)
        self.login.setObjectName("login")
        self.label = QtWidgets.QLabel(Login)
        self.label.setGeometry(QtCore.QRect(20, 90, 221, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.password = QtWidgets.QLineEdit(Login)
        self.password.setGeometry(QtCore.QRect(20, 180, 221, 22))
        self.password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.password.setObjectName("password")

        self.retranslateUi(Login)
        QtCore.QMetaObject.connectSlotsByName(Login)

    def retranslateUi(self, Login):
        _translate = QtCore.QCoreApplication.translate
        Login.setWindowTitle(_translate("Login", "Логинка"))
        self.enterButton.setText(_translate("Login", "Войти"))
        self.login.setPlaceholderText(_translate("Login", "Логин"))
        self.label.setText(_translate("Login", "А ты точно наш сотрудник?"))
        self.password.setPlaceholderText(_translate("Login", "Пароль"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Login = QtWidgets.QDialog()
    ui = Ui_Login()
    ui.setupUi(Login)
    Login.show()
    sys.exit(app.exec_())
